[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[functions]
  directory = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[dev]
  command = "uvicorn app:app --reload"
